# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: <a>http://www.numpy.org/</a>

In [1]:
import numpy as np

# Task 1: declare a vector using a list as the argument

In [2]:
A = []

# Task 2: declare a matrix using a nested list as the argument

In [4]:
B = [[]]

# Task 3: initialize x or x and y using the following functions: arange, linspace, logspace, mgrid

In [38]:
x = np.arange(3)
y = np.linspace(1,10,10)
z = np.logspace(1,10,10)
p = np.mgrid[0:5,0:5]
print (p.shape)

(2, 5, 5)


# Task 4: what is difference between random.rand and random.randn

In [43]:
r = np.random.rand(1,10) 
#Create an array of a certain shape containing random samples from a uniform distribution.

np.random.randn
#Can provide a distribution of random samples from a standard normal distribution.

# Task 5: what are the funciotns diag, itemsize, nbytes and ndim about?

In [51]:
#np.diag()
# Can be used to extract the diagonal from a matrix or to create a diagonal matrix
#np.ndarray.itemsize
#Gives the length of an array in bytes. 
#np.ndarray.nbytes?
#Gives the total amount of bytes consumed by the elements of the array.
#np.ndarray.ndim?
#Produces the number of array dimensions.


In [77]:
# assign new value
M = np.array([[1,2,3],[4,5,6],[7,8,9]])
M[0,0] = 7

array([[7, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [80]:
M = np.arange


<function numpy.core.multiarray.arange>

In [79]:
M[0,:] = 0

TypeError: 'builtin_function_or_method' object does not support item assignment

In [124]:
# slicing works just like with lists
A = np.array([1,2,3,4,5])
A[1:3]

array([2, 3])

# Task 6: Using list comprehensions create the following matrix
array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [102]:
m = np.array([[i + j for j in range(0,5,1)]for i in range(0,50,10)])
print(m)


[[ 0  1  2  3  4]
 [10 11 12 13 14]
 [20 21 22 23 24]
 [30 31 32 33 34]
 [40 41 42 43 44]]


In [104]:
row_indices = [1, 2, 3]
A[row_indices]

TypeError: 'builtin_function_or_method' object is not subscriptable

In [107]:
# index masking
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [108]:
v1 = np.arange(0, 5)

In [109]:
v1 + 2

array([2, 3, 4, 5, 6])

In [110]:
v1 * 2

array([0, 2, 4, 6, 8])

In [111]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [113]:
np.dot(v1, v1)

30

In [114]:
np.dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [115]:
# cast changes behavior of + - * etc. to use matrix algebra
M = np.matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [118]:
# inner product
v1.T * v1

array([ 0,  1,  4,  9, 16])

In [120]:
C = np.matrix([[1j, 2j], [3j, 4j]])

In [121]:
np.conjugate(C)

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

In [122]:
# inverse
C.I

matrix([[0.+2.j , 0.-1.j ],
        [0.-1.5j, 0.+0.5j]])

### Statistics

In [127]:
print(A)
p.mean(A[:,3])

[1 2 3 4 5]


IndexError: too many indices for array

In [ ]:
std(A[:,3]), var(A[:,3])

In [ ]:
A[:,3].min(), A[:,3].max()

In [ ]:
d = arange(1, 10)
sum(d), prod(d)

In [ ]:
cumsum(d)

In [ ]:
cumprod(d)

In [ ]:
# sum of diagonal
trace(A)

In [ ]:
m = random.rand(3, 3)

In [ ]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

In [ ]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

In [ ]:
# modify the array
B[0,0:5] = 5

In [ ]:
# also changed
A

In [ ]:
# creates a copy
B = A.flatten()

In [ ]:
# can insert a dimension in an array
v = array([1,2,3])
v[:, newaxis], v[:,newaxis].shape, v[newaxis,:].shape

In [ ]:
repeat(v, 3)

In [ ]:
tile(v, 3)

In [ ]:
w = array([5, 6])

In [ ]:
concatenate((v, w), axis=0)

In [ ]:
# deep copy
B = copy(A)